version: '3.8'

services:
  cliphawk-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/temp_downloads:/app/temp_downloads
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - PYTHONASYNCIODEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 